[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "lark>=1.3.1",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "rich>=14.2.0",
    "typer>=0.21.1",
]
